#!/usr/bin/env python3
"""Fill .ts translation files with translations."""
import xml.etree.ElementTree as ET

EN_TO_ZH = {
    "Text Translation": "文本翻译",
    "Selection Translation": "划词翻译",
    "Screenshot Translation": "截图翻译",
    "Image Translation": "图片翻译",
    "File Translation": "文件翻译",
    "Settings": "设置",
    "Translate": "翻译",
    "Translating…": "翻译中…",
    "Translation Result": "翻译结果",
    "Translation Result…": "翻译结果…",
    "Translation engine error: ": "翻译引擎错误: ",
    "File translation error: ": "文件翻译错误: ",
    "Screenshot translation error: ": "截图翻译错误: ",
    "Image translation error: ": "图片翻译错误: ",
    "Translation error: ": "翻译出错: ",
    "Translator": "翻译引擎",
    "Translation Model": "翻译模型",
    "Translation History": "翻译历史",
    "Read Aloud": "朗读",
    "Copy": "复制",
    "Paste": "粘贴",
    "Clear": "清空",
    "Cancel": "取消",
    "OK": "确定",
    "Prompt": "提示",
    "Error": "错误",
    "Warning": "警告",
    "Done": "完成",
    "Waiting for screenshot…": "等待截图…",
    "Upload File": "上传文件",
    "Select File": "选择文件",
    "Save": "保存",
    "Delete": "删除",
    "Add": "添加",
    "Upload": "上传",
    "Download": "下载",
    "Model": "模型",
    "Engine": "引擎",
    "Start": "启动",
    "Stop": "停止",
    "Load": "加载",
    "Recognize": "识别",
    "Status": "状态",
    "Source Language:": "源语言:",
    "Target Language:": "目标语言:",
    "Source Text": "原文",
    "Auto Detect": "自动检测",
    "Auto Copy": "自动复制",
    "Stay on Top": "窗口置顶",
    "Default Language": "默认语言",
    "Hotkey": "快捷键",
    "Hotkey Conflict": "快捷键冲突",
    "Screenshot Preview": "截图预览",
    "Recognition Result": "识别结果",
    "OCR Text…": "OCR 识别文本…",
    "Recognizing…": "OCR 识别截图…",
    "Screenshot is empty": "截图图像为空",
    "Enter text to translate…": "请输入要翻译的文本…",
    "0 characters": "0 字符",
    "%1 characters": "%1 字符",
    "Ready": "就绪",
    "Processing, please wait…": "正在处理中，请等待…",
    "Loading config…": "正在加载配置…",
    "Loading engines…": "正在加载引擎…",
    "Engines loaded": "引擎加载完成",
    "Initializing UI…": "正在初始化界面…",
    "Startup complete": "启动完成",
    "AceTranslatePro is already running.": "AceTranslatePro 已在运行中，请勿重复启动。",
    "Set Selection Hotkey": "设置划词翻译快捷键",
    "Set Screenshot Hotkey": "设置截图快捷键",
    "Selected text will appear here…": "选中的文本将显示在这里…",
    "Translation result will appear here…": "翻译结果将显示在这里…",
    "Translation history will appear here…": "划词翻译记录将显示在这里…",
    "Translating…": "正在翻译…",
    "Copied": "译文已复制",
    "Current Text": "当前文本",
    "Deskew": "去扭曲",
    "Enhance": "增强",
    "Layout Threshold:": "版面阈值:",
    "DPI:": "DPI:",
    "File List": "上传文件列表",
    "Translation Complete": "翻译完成",
    "Downloaded to: ": "已下载到: ",
    "Save Failed": "保存失败",
    "Load Engines on Startup": "启动时加载引擎",
    "OCR Engine": "OCR 引擎",
    "Formula Recognition": "公式识别",
    "Layout Analysis": "版面分析",
    "Image Correction": "图片矫正",
    "Speech Recognition": "语音识别",
    "GPU Settings": "GPU 设置",
    "Enable All GPU Acceleration": "启用全部 GPU 加速",
    "Layout GPU": "版面分析启用 GPU",
    "OCR GPU": "OCR 启用 GPU",
    "VLM GPU": "公式识别启用 GPU",
    "Image Correction GPU": "图片矫正启用 GPU",
    "Translator GPU": "翻译引擎启用 GPU",
    "ASR GPU": "语音识别启用 GPU",
    "OCR Model Size:": "OCR 模型大小:",
    "Tiny": "tiny（轻量）",
    "Small": "small（中等）",
    "Medium": "medium（高精度）",
    "Translation Model:": "翻译模型:",
    "Refresh Models": "刷新模型列表",
    "Screenshot Unavailable": "截图翻译不可用",
    "Recording… click to stop": "录音中…点击 \U0001f3a4 停止",
    "Test mode: reading test.wav…": "测试模式：读取 test.wav…",
    "Screenshot cancelled": "截图取消",
    "Image is empty": "图片为空",
    "Open in Folder": "在文件夹中打开",
    "All Files (*)": "所有文件 (*)",
    "Characters": "字符",
    "Set Hotkey": "设置快捷键",
    "Hide": "隐藏",
    "Show": "显示",
    "Help": "帮助",
    "About": "关于",
    "Close": "关闭",
    "Retry": "重试",
    "All": "全部",
    "None": "无",
    "ON": "开",
    "OFF": "关",
    "Edit": "编辑",
    "Chinese": "中文",
    "English": "英语",
    "Japanese": "日语",
    "Korean": "韩语",
    "French": "法语",
    "German": "德语",
    "Spanish": "西班牙语",
    "Russian": "俄语",
    "Arabic": "阿拉伯语",
    "Portuguese": "葡萄牙语",
    "Italian": "意大利语",
    "Thai": "泰语",
    "Vietnamese": "越南语",
    "Indonesian": "印尼语",
    "Malay": "马来语",
    "Filipino": "菲律宾语",
    "Hindi": "印地语",
    "Traditional Chinese": "繁体中文",
    "Polish": "波兰语",
    "Czech": "捷克语",
    "Dutch": "荷兰语",
    "Khmer": "高棉语",
    "Burmese": "缅甸语",
    "Persian": "波斯语",
    "Gujarati": "古吉拉特语",
    "Urdu": "乌尔都语",
    "Telugu": "泰卢固语",
    "Marathi": "马拉地语",
    "Hebrew": "希伯来语",
    "Bengali": "孟加拉语",
    "Tamil": "泰米尔语",
    "Ukrainian": "乌克兰语",
    "Tibetan": "藏语",
    "Kazakh": "哈萨克语",
    "Mongolian": "蒙古语",
    "Uyghur": "维吾尔语",
    "Cantonese": "粤语",
    "Turkish": "土耳其语",
    "Malayalam": "马拉雅拉姆语",
    "Kannada": "卡纳达语",
    "Punjabi": "旁遮普语",
    "Enter or paste text to translate": "输入或粘贴文本，快速翻译到目标语言",
    "Select text in any app, press hotkey to translate": "选中任意应用中的文字，按快捷键弹出翻译窗口",
    "Drag or select input file": "请拖拽或选择输入文件",
    "Enter text to translate": "请输入要翻译的文本",
    "Select input image": "请选择输入图片",
    "Select Image": "选择图片",
    "Select Model/DLL Directory": "选择模型/DLL 目录",
    "Microphone open failed": "麦克风打开失败",
    "Voice Input": "语音输入",
    "Speech recognition…": "语音识别中…",
    "Speech complete": "语音识别完成",
    "ASR DLL Interface Error": "ASR DLL 接口错误",
    "ASR Engine Not Loaded": "ASR 引擎未加载",
    "ASR Model Load Failed": "ASR 模型加载失败",
    "Voice %1 not found": "未找到 %1 语音包",
    "Drag image here or click to upload": "拖拽图片到此处，或点击上传",
    "Image preview…": "拖拽图片预览…",
    "Drag files here or click to upload": "拖拽文件到此处，或点击上传",
    "Translate Image": "翻译图片",
    "Translating image…": "翻译图片…",
    "Result shows after translation…": "翻译完成后显示结果…",
    "Original": "原图",
    "Image saved: ": "图片已保存: ",
    "Image copied": "图片已复制",
    "Save Image": "保存图片",
    "Save Image Failed": "保存图片失败",
    "Zoom In": "放大",
    "Zoom Out": "缩小",
    "Image": "图片",
    "Text": "文本",
    "File": "文件",
    "Large": "大",
    "Processing…": "处理中…",
    "Processing: ": "处理文件: ",
    "Completed": "已完成",
    "Queued": "排队中",
    "All %1 files translated": "全部翻译完成（共 %1 个文件）",
    " Translation Complete": " 翻译完成",
    " Translation Complete: %1": " 翻译完成: %1",
    "OCR Model Size": "OCR 模型大小",
    "Open Settings": "打开设置",
    "Show Main Window": "显示主窗口",
    "Exit": "退出",
    "Test mode: test.wav not found": "测试模式：找不到 test.wav",
    "Test mode: loaded, recognizing": "测试模式：读取完成，开始识别",
    "Click to stop recording": "点击停止录音",
    "Requires restart": "修改后需重启应用生效",
    "Save File": "保存文件",
    "Supports PDF / Word / Excel / PPT / MD / TXT / Images": "支持 PDF / Word / Excel / PPT / MD / TXT / 图片",
    "Cannot load image": "无法加载图片",
    "Cannot load preview": "无法加载预览",
    "PNG Images (*.png)": "PNG 图片 (*.png)",
    "Language": "界面语言",
    "Language change takes effect after restart": "语言切换将在重启后生效",
    "Unknown error (DLL load failure)": "未知错误（可能是 DLL 加载失败）",
    "Translation Error": "翻译出错",
    "AceTranslatePro": "AceTranslatePro",
}

EN_TO_JA = {
    # === 导航栏 ===
    "Text Translation": "テキスト翻訳",
    "Selection Translation": "選択翻訳",
    "Screenshot Translation": "スクリーンショット翻訳",
    "Image Translation": "画像翻訳",
    "File Translation": "ファイル翻訳",
    "Settings": "設定",

    # === 通用 ===
    "Translate": "翻訳",
    "Translating…": "翻訳中…",
    "Translation Result": "翻訳結果",
    "Translation Result…": "翻訳結果…",
    "Translation engine error: ": "翻訳エンジンエラー: ",
    "File translation error: ": "ファイル翻訳エラー: ",
    "Screenshot translation error: ": "スクリーンショット翻訳エラー: ",
    "Image translation error: ": "画像翻訳エラー: ",
    "Translation error: ": "翻訳エラー: ",
    "Translator": "翻訳エンジン",
    "Translation Model": "翻訳モデル",
    "Translation History": "翻訳履歴",
    "Read Aloud": "読み上げ",
    "Copy": "コピー",
    "Paste": "ペースト",
    "Clear": "クリア",
    "Cancel": "キャンセル",
    "OK": "OK",
    "Prompt": "ヒント",
    "Error": "エラー",
    "Warning": "警告",
    "Done": "完了",
    "Waiting for screenshot…": "スクリーンショット待機中…",
    "Upload File": "ファイルアップロード",
    "Select File": "ファイル選択",
    "Save": "保存",
    "Delete": "削除",
    "Add": "追加",
    "Upload": "アップロード",
    "Download": "ダウンロード",
    "Model": "モデル",
    "Engine": "エンジン",
    "Start": "開始",
    "Stop": "停止",
    "Load": "読み込み",
    "Recognize": "認識",
    "Status": "ステータス",
    "Source Language:": "ソース言語:",
    "Target Language:": "ターゲット言語:",
    "Source Text": "原文",
    "Auto Detect": "自動検出",
    "Auto Copy": "自動コピー",
    "Stay on Top": "最前面に表示",
    "Default Language": "デフォルト言語",
    "Hotkey": "ショートカットキー",
    "Hotkey Conflict": "ショートカットキー競合",
    "Screenshot Preview": "スクリーンショットプレビュー",
    "Recognition Result": "認識結果",
    "OCR Text…": "OCRテキスト…",
    "Recognizing…": "OCR認識中…",
    "Screenshot is empty": "スクリーンショットが空です",
    "Enter text to translate…": "翻訳するテキストを入力…",
    "0 characters": "0文字",
    "%1 characters": "%1文字",
    "Characters": "文字数",
    "Ready": "準備完了",
    "Processing, please wait…": "処理中、お待ちください…",
    "Loading config…": "設定を読み込み中…",
    "Loading engines…": "エンジンを読み込み中…",
    "Engines loaded": "エンジン読み込み完了",
    "Initializing UI…": "UIを初期化中…",
    "Startup complete": "起動完了",
    "AceTranslatePro is already running.": "AceTranslateProは既に起動しています。",
    "Set Selection Hotkey": "選択翻訳ショートカット設定",
    "Set Screenshot Hotkey": "スクリーンショットショートカット設定",
    "Selected text will appear here…": "選択したテキストがここに表示されます…",
    "Translation result will appear here…": "翻訳結果がここに表示されます…",
    "Translation history will appear here…": "翻訳履歴がここに表示されます…",
    "Copied": "コピーしました",
    "Current Text": "現在のテキスト",
    "Deskew": "傾き補正",
    "Enhance": "強調",
    "Layout Threshold:": "レイアウトしきい値:",
    "DPI:": "DPI:",
    "File List": "ファイル一覧",
    "Translation Complete": "翻訳完了",
    " Translation Complete": " 翻訳完了",
    " Translation Complete: %1": " 翻訳完了: %1",
    "Downloaded to: ": "ダウンロード先: ",
    "Save Failed": "保存失敗",
    "Load Engines on Startup": "起動時にエンジンを読み込む",
    "OCR Engine": "OCRエンジン",
    "Formula Recognition": "数式認識",
    "Layout Analysis": "レイアウト解析",
    "Image Correction": "画像補正",
    "Speech Recognition": "音声認識",
    "GPU Settings": "GPU設定",
    "Enable All GPU Acceleration": "すべてのGPUアクセラレーションを有効化",
    "Layout GPU": "レイアウト解析GPU",
    "OCR GPU": "OCR GPU",
    "VLM GPU": "数式認識GPU",
    "Image Correction GPU": "画像補正GPU",
    "Translator GPU": "翻訳エンジンGPU",
    "ASR GPU": "音声認識GPU",
    "OCR Model Size": "OCRモデルサイズ",
    "OCR Model Size:": "OCRモデルサイズ:",
    "Tiny": "軽量",
    "Small": "標準",
    "Medium": "高精度",
    "Large": "大",
    "Translation Model:": "翻訳モデル:",
    "Refresh Models": "モデル一覧更新",
    "Screenshot Unavailable": "スクリーンショット利用不可",
    "Recording… click to stop": "録音中…クリックして停止",
    "Test mode: reading test.wav…": "テストモード：test.wavを読み込み中…",
    "Screenshot cancelled": "キャンセルしました",
    "Image is empty": "画像が空です",
    "Open in Folder": "フォルダを開く",
    "All Files (*)": "すべてのファイル (*)",
    "Characters": "文字数",
    "Set Hotkey": "ショートカット設定",
    "Hide": "非表示",
    "Show": "表示",
    "Help": "ヘルプ",
    "About": "情報",
    "Close": "閉じる",
    "Retry": "リトライ",
    "All": "すべて",
    "None": "なし",
    "ON": "ON",
    "OFF": "OFF",
    "Edit": "編集",
    "Chinese": "中国語",
    "English": "英語",
    "Japanese": "日本語",
    "Korean": "韓国語",
    "French": "フランス語",
    "German": "ドイツ語",
    "Spanish": "スペイン語",
    "Russian": "ロシア語",
    "Arabic": "アラビア語",
    "Portuguese": "ポルトガル語",
    "Italian": "イタリア語",
    "Thai": "タイ語",
    "Vietnamese": "ベトナム語",
    "Indonesian": "インドネシア語",
    "Malay": "マレー語",
    "Filipino": "フィリピノ語",
    "Hindi": "ヒンディー語",
    "Traditional Chinese": "繁体字中国語",
    "Polish": "ポーランド語",
    "Czech": "チェコ語",
    "Dutch": "オランダ語",
    "Khmer": "クメール語",
    "Burmese": "ビルマ語",
    "Persian": "ペルシア語",
    "Gujarati": "グジャラート語",
    "Urdu": "ウルドゥー語",
    "Telugu": "テルグ語",
    "Marathi": "マラーティー語",
    "Hebrew": "ヘブライ語",
    "Bengali": "ベンガル語",
    "Tamil": "タミル語",
    "Ukrainian": "ウクライナ語",
    "Tibetan": "チベット語",
    "Kazakh": "カザフ語",
    "Mongolian": "モンゴル語",
    "Uyghur": "ウイグル語",
    "Cantonese": "広東語",
    "Turkish": "トルコ語",
    "Malayalam": "マラヤーラム語",
    "Kannada": "カンナダ語",
    "Punjabi": "パンジャブ語",

    # === 描述文本 ===
    "Enter or paste text to translate": "テキストを入力または貼り付けて翻訳",
    "Select text in any app, press hotkey to translate": "アプリのテキストを選択、ショートカットキーで翻訳",
    "Drag or select input file": "ファイルをドラッグまたは選択",
    "Enter text to translate": "翻訳するテキストを入力",
    "Select input image": "画像を選択",
    "Select Image": "画像を選択",
    "Select Model/DLL Directory": "モデル/DLLディレクトリ選択",
    "Microphone open failed": "マイクの起動に失敗しました",
    "Voice Input": "音声入力",
    "Speech recognition…": "音声認識中…",
    "Speech complete": "音声認識完了",
    "ASR DLL Interface Error": "ASR DLLインターフェースエラー",
    "ASR Engine Not Loaded": "ASRエンジン未読み込み",
    "ASR Model Load Failed": "ASRモデル読み込み失敗",
    "Voice %1 not found": "%1 音声パッケージが見つかりません",
    "Drag image here or click to upload": "画像をドラッグ、またはクリックしてアップロード",
    "Image preview…": "画像プレビュー…",
    "Drag files here or click to upload": "ファイルをドラッグ、またはクリックしてアップロード",
    "Translate Image": "画像を翻訳",
    "Translating image…": "画像翻訳中…",
    "Result shows after translation…": "翻訳完了後に結果を表示…",
    "Original": "原図",
    "Image saved: ": "画像を保存: ",
    "Image copied": "画像をコピー",
    "Save Image": "画像を保存",
    "Save Image Failed": "画像保存失敗",
    "Zoom In": "拡大",
    "Zoom Out": "縮小",
    "Image": "画像",
    "Text": "テキスト",
    "File": "ファイル",
    "Processing…": "処理中…",
    "Processing: ": "処理中: ",
    "Completed": "完了",
    "Queued": "待機中",
    "All %1 files translated": "全%1ファイル翻訳完了",
    "Open Settings": "設定を開く",
    "Show Main Window": "メインウィンドウを表示",
    "Exit": "終了",
    "Test mode: test.wav not found": "テストモード：test.wavが見つかりません",
    "Test mode: loaded, recognizing": "テストモード：読み込み完了、認識中",
    "Click to stop recording": "クリックして録音停止",
    "Requires restart": "再起動が必要です",
    "Save File": "ファイル保存",
    "Supports PDF / Word / Excel / PPT / MD / TXT / Images": "対応形式: PDF / Word / Excel / PPT / MD / TXT / 画像",
    "Cannot load image": "画像を読み込めません",
    "Cannot load preview": "プレビューを読み込めません",
    "PNG Images (*.png)": "PNG画像 (*.png)",
    "Language": "言語",
    "Language change takes effect after restart": "言語変更は再起動後に反映されます",
    "Unknown error (DLL load failure)": "不明なエラー（DLL読み込み失敗）",
    "Translation Error": "翻訳エラー",
    "AceTranslatePro": "AceTranslatePro",

    # === 设置页面额外 ===
    "Disable to reduce startup time. Engines load on demand.": "無効にすると起動時間を短縮。エンジンは必要時に読み込み。",
    "Disable GPU to reduce VRAM. Restart required.": "GPUを無効にしてVRAMを節約。再起動が必要。",
    "Press new hotkey (Ctrl or Alt required)": "新しいショートカットキーを押してください（CtrlまたはAlt必須）",
    "This hotkey is used by Selection Translation.": "このショートカットキーは選択翻訳で使用されています。",
    "This hotkey is used by Screenshot Translation.": "このショートカットキーはスクリーンショット翻訳で使用されています。",
    "Hotkey Registration Failed": "ショートカットキー登録失敗",
    "Capture screen area for OCR and translation": "画面領域をキャプチャしてOCR翻訳",
    "OCR engine failed to load. Please check if model files exist.\nPath: models/ocr/[tiny/small/medium]/": "OCRエンジンの読み込みに失敗しました。モデルファイルを確認してください。\nパス: models/ocr/[tiny/small/medium]/",
    "Screenshot Unavailable": "スクリーンショット利用不可",
}

def fill_ts(ts_path, trans_map):
    tree = ET.parse(ts_path)
    root = tree.getroot()
    n = 0
    for ctx in root.findall('context'):
        for msg in ctx.findall('message'):
            src_el = msg.find('source')
            tr_el = msg.find('translation')
            if src_el is None or tr_el is None:
                continue
            src = src_el.text or ''
            if src in trans_map:
                tr_el.text = trans_map[src]
                tr_el.set('type', 'unfinished')
                n += 1
    tree.write(ts_path, encoding='utf-8', xml_declaration=True)
    return n

base = 'd:/AceTranslatePro/AceTranslatePro/translations'

# en_US: source = translation (identity)
tree = ET.parse(f'{base}/en_US.ts')
for msg in tree.findall('.//message'):
    src = msg.find('source')
    tr = msg.find('translation')
    if src is not None and tr is not None:
        tr.text = src.text
        tr.set('type', 'unfinished')
tree.write(f'{base}/en_US.ts', encoding='utf-8', xml_declaration=True)

c1 = fill_ts(f'{base}/zh_CN.ts', EN_TO_ZH)
c2 = fill_ts(f'{base}/ja_JP.ts', EN_TO_JA)
print(f'zh_CN: {c1}')
print(f'ja_JP: {c2}')
print('en_US: identity')
