#!/usr/bin/env python3
"""Replace Chinese translations in ja_JP.ts with proper Japanese translations."""
import xml.etree.ElementTree as ET

JA_DICT = {
    # === 导航栏 ===
    'Text Translation': 'テキスト翻訳',
    'Selection Translation': '選択翻訳',
    'Screenshot Translation': 'スクリーンショット翻訳',
    'Image Translation': '画像翻訳',
    'File Translation': 'ファイル翻訳',
    'Settings': '設定',

    # === 通用 ===
    'Translate': '翻訳',
    'Translating…': '翻訳中…',
    'Translation Result': '翻訳結果',
    'Translation Result…': '翻訳結果…',
    'Translation engine error: ': '翻訳エンジンエラー: ',
    'File translation error: ': 'ファイル翻訳エラー: ',
    'Screenshot translation error: ': 'スクリーンショット翻訳エラー: ',
    'Image translation error: ': '画像翻訳エラー: ',
    'Translation error: ': '翻訳エラー: ',
    'Translator': '翻訳エンジン',
    'Translation Model': '翻訳モデル',
    'Translation History': '翻訳履歴',
    'Read Aloud': '読み上げ',
    'Copy': 'コピー',
    'Paste': 'ペースト',
    'Clear': 'クリア',
    'Cancel': 'キャンセル',
    'OK': 'OK',
    'Prompt': 'ヒント',
    'Error': 'エラー',
    'Warning': '警告',
    'Done': '完了',
    'Waiting for screenshot…': 'スクリーンショット待機中…',
    'Upload File': 'ファイルアップロード',
    'Select File': 'ファイル選択',
    'Save': '保存',
    'Delete': '削除',
    'Add': '追加',
    'Upload': 'アップロード',
    'Download': 'ダウンロード',
    'Model': 'モデル',
    'Engine': 'エンジン',
    'Start': '開始',
    'Stop': '停止',
    'Load': '読み込み',
    'Recognize': '認識',
    'Status': 'ステータス',
    'Source Language:': 'ソース言語:',
    'Target Language:': 'ターゲット言語:',
    'Source Text': '原文',
    'Auto Detect': '自動検出',
    'Auto Copy': '自動コピー',
    'Stay on Top': '最前面に表示',
    'Default Language': 'デフォルト言語',
    'Hotkey': 'ショートカットキー',
    'Hotkey Conflict': 'ショートカットキー競合',
    'Screenshot Preview': 'スクリーンショットプレビュー',
    'Recognition Result': '認識結果',
    'OCR Text…': 'OCRテキスト…',
    'Recognizing…': 'OCR認識中…',
    'Screenshot is empty': 'スクリーンショットが空です',
    'Enter text to translate…': '翻訳するテキストを入力…',
    '0 characters': '0文字',
    'Ready': '準備完了',
    'Processing, please wait…': '処理中、お待ちください…',
    'Loading config…': '設定を読み込み中…',
    'Loading engines…': 'エンジンを読み込み中…',
    'Engines loaded': 'エンジン読み込み完了',
    'Initializing UI…': 'UIを初期化中…',
    'Startup complete': '起動完了',
    'AceTranslatePro is already running.': 'AceTranslateProは既に起動しています。',
    'Set Selection Hotkey': '選択翻訳ショートカット設定',
    'Set Screenshot Hotkey': 'スクリーンショットショートカット設定',
    'Selected text will appear here…': '選択したテキストがここに表示されます…',
    'Translation result will appear here…': '翻訳結果がここに表示されます…',
    'Translation history will appear here…': '翻訳履歴がここに表示されます…',
    'Copied': 'コピーしました',
    'Current Text': '現在のテキスト',
    'Deskew': '傾き補正',
    'Enhance': '強調',
    'Layout Threshold:': 'レイアウトしきい値:',
    'DPI:': 'DPI:',
    'File List': 'ファイル一覧',
    'Translation Complete': '翻訳完了',
    ' Translation Complete': ' 翻訳完了',
    ' Translation Complete: %1': ' 翻訳完了: %1',
    'Downloaded to: ': 'ダウンロード先: ',
    'Save Failed': '保存失敗',
    'Load Engines on Startup': '起動時にエンジンを読み込む',
    'OCR Engine': 'OCRエンジン',
    'Formula Recognition': '数式認識',
    'Layout Analysis': 'レイアウト解析',
    'Image Correction': '画像補正',
    'Speech Recognition': '音声認識',
    'GPU Settings': 'GPU設定',
    'Enable All GPU Acceleration': 'すべてのGPUアクセラレーションを有効化',
    'Layout GPU': 'レイアウト解析GPU',
    'OCR GPU': 'OCR GPU',
    'VLM GPU': '数式認識GPU',
    'Image Correction GPU': '画像補正GPU',
    'Translator GPU': '翻訳エンジンGPU',
    'ASR GPU': '音声認識GPU',
    'OCR Model Size': 'OCRモデルサイズ',
    'OCR Model Size:': 'OCRモデルサイズ:',
    'Tiny': '軽量',
    'Small': '標準',
    'Medium': '高精度',
    'Large': '大',
    'Translation Model:': '翻訳モデル:',
    'Refresh Models': 'モデル一覧更新',
    'Screenshot Unavailable': 'スクリーンショット利用不可',
    'Recording… click to stop': '録音中…クリックして停止',
    'Test mode: reading test.wav…': 'テストモード：test.wavを読み込み中…',
    'Screenshot cancelled': 'キャンセルしました',
    'Image is empty': '画像が空です',
    'Open in Folder': 'フォルダを開く',
    'All Files (*)': 'すべてのファイル (*)',
    'Characters': '文字',
    'Set Hotkey': 'ショートカット設定',
    'Hide': '非表示',
    'Show': '表示',
    'Help': 'ヘルプ',
    'About': '情報',
    'Close': '閉じる',
    'Retry': 'リトライ',
    'All': 'すべて',
    'None': 'なし',
    'ON': 'ON',
    'OFF': 'OFF',
    'Edit': '編集',

    # === 语言名称 ===
    'Chinese': '中国語',
    'English': '英語',
    'Japanese': '日本語',
    'Korean': '韓国語',
    'French': 'フランス語',
    'German': 'ドイツ語',
    'Spanish': 'スペイン語',
    'Russian': 'ロシア語',
    'Arabic': 'アラビア語',
    'Portuguese': 'ポルトガル語',
    'Italian': 'イタリア語',
    'Thai': 'タイ語',
    'Vietnamese': 'ベトナム語',
    'Indonesian': 'インドネシア語',
    'Malay': 'マレー語',
    'Filipino': 'フィリピノ語',
    'Hindi': 'ヒンディー語',
    'Traditional Chinese': '繁体字中国語',
    'Polish': 'ポーランド語',
    'Czech': 'チェコ語',
    'Dutch': 'オランダ語',
    'Khmer': 'クメール語',
    'Burmese': 'ビルマ語',
    'Persian': 'ペルシア語',
    'Gujarati': 'グジャラート語',
    'Urdu': 'ウルドゥー語',
    'Telugu': 'テルグ語',
    'Marathi': 'マラーティー語',
    'Hebrew': 'ヘブライ語',
    'Bengali': 'ベンガル語',
    'Tamil': 'タミル語',
    'Ukrainian': 'ウクライナ語',
    'Tibetan': 'チベット語',
    'Kazakh': 'カザフ語',
    'Mongolian': 'モンゴル語',
    'Uyghur': 'ウイグル語',
    'Cantonese': '広東語',
    'Turkish': 'トルコ語',
    'Malayalam': 'マラヤーラム語',
    'Kannada': 'カンナダ語',
    'Punjabi': 'パンジャブ語',

    # === 描述文本 ===
    'Enter or paste text to translate': 'テキストを入力または貼り付けて翻訳',
    'Select text in any app, press hotkey to translate': 'アプリのテキストを選択、ショートカットキーで翻訳',
    'Drag or select input file': 'ファイルをドラッグまたは選択',
    'Enter text to translate': '翻訳するテキストを入力',
    'Select input image': '画像を選択',
    'Select Image': '画像を選択',
    'Select Model/DLL Directory': 'モデル/DLLディレクトリ選択',
    'Microphone open failed': 'マイクの起動に失敗しました',
    'Voice Input': '音声入力',
    'Speech recognition…': '音声認識中…',
    'Speech complete': '音声認識完了',
    'ASR DLL Interface Error': 'ASR DLLインターフェースエラー',
    'ASR Engine Not Loaded': 'ASRエンジン未読み込み',
    'ASR Model Load Failed': 'ASRモデル読み込み失敗',
    'Voice %1 not found': '%1 音声パッケージが見つかりません',
    'Drag image here or click to upload': '画像をドラッグ、またはクリックしてアップロード',
    'Image preview…': '画像プレビュー…',
    'Drag files here or click to upload': 'ファイルをドラッグ、またはクリックしてアップロード',
    'Translate Image': '画像を翻訳',
    'Translating image…': '画像翻訳中…',
    'Result shows after translation…': '翻訳完了後に結果を表示…',
    'Original': '原図',
    'Image saved: ': '画像を保存: ',
    'Image copied': '画像をコピー',
    'Save Image': '画像を保存',
    'Save Image Failed': '画像保存失敗',
    'Zoom In': '拡大',
    'Zoom Out': '縮小',
    'Image': '画像',
    'Text': 'テキスト',
    'File': 'ファイル',
    'Processing…': '処理中…',
    'Processing: ': '処理中: ',
    'Completed': '完了',
    'Queued': '待機中',
    'All %1 files translated': '全%1ファイル翻訳完了',
    'Open Settings': '設定を開く',
    'Show Main Window': 'メインウィンドウを表示',
    'Exit': '終了',
    'Test mode: test.wav not found': 'テストモード：test.wavが見つかりません',
    'Test mode: loaded, recognizing': 'テストモード：読み込み完了、認識中',
    'Click to stop recording': 'クリックして録音停止',
    'Requires restart': '再起動が必要です',
    'Save File': 'ファイル保存',
    'Supports PDF / Word / Excel / PPT / MD / TXT / Images': '対応形式: PDF / Word / Excel / PPT / MD / TXT / 画像',
    'Cannot load image': '画像を読み込めません',
    'Cannot load preview': 'プレビューを読み込めません',
    'PNG Images (*.png)': 'PNG画像 (*.png)',
    'Language': '言語',
    'Language change takes effect after restart': '言語変更は再起動後に反映されます',
    'Unknown error (DLL load failure)': '不明なエラー（DLL読み込み失敗）',
    'Translation Error': '翻訳エラー',
    'AceTranslatePro': 'AceTranslatePro',
    'Characters': '文字数',

    # === 设置页面 ===
    'Disable to reduce startup time. Engines load on demand.': '無効にすると起動時間を短縮。エンジンは必要時に読み込み。',
    'Disable GPU to reduce VRAM. Restart required.': 'GPUを無効にしてVRAMを節約。再起動が必要。',
    'Press new hotkey (Ctrl or Alt required)': '新しいショートカットキーを押してください（CtrlまたはAlt必須）',
    'This hotkey is used by Selection Translation.': 'このショートカットキーは選択翻訳で使用されています。',
    'This hotkey is used by Screenshot Translation.': 'このショートカットキーはスクリーンショット翻訳で使用されています。',
    'Hotkey Registration Failed': 'ショートカットキー登録失敗',
    'Capture screen area for OCR and translation': '画面領域をキャプチャしてOCR翻訳',
    '%1 characters': '%1文字',
    'OCR engine failed to load. Please check if model files exist.\nPath: models/ocr/[tiny/small/medium]/': 'OCRエンジンの読み込みに失敗しました。モデルファイルを確認してください。\nパス: models/ocr/[tiny/small/medium]/',
    'OCR engine failed to load. Please check if model files exist.\nPath: models/ocr/[tiny/small/medium]/': 'OCRエンジンの読み込みに失敗しました。モデルファイルを確認してください。\nパス: models/ocr/[tiny/small/medium]/',
    'Select text in any app, press hotkey to translate': 'アプリのテキストを選択、ショートカットキーで翻訳',
}

tree = ET.parse('translations/ja_JP.ts')
root = tree.getroot()
n = 0
for ctx in root.findall('context'):
    for msg in ctx.findall('message'):
        src_el = msg.find('source')
        tr_el = msg.find('translation')
        if src_el is None or tr_el is None:
            continue
        src = src_el.text or ''
        if src in JA_DICT:
            tr_el.text = JA_DICT[src]
            n += 1
tree.write('translations/ja_JP.ts', encoding='utf-8', xml_declaration=True)
print(f'Updated {n} entries in ja_JP.ts')
