#!/usr/bin/env python3
"""将 ui/ 下所有 QStringLiteral("中文") 替换为 tr("英文key")"""

import re
import os

ui_dir = 'd:/AceTranslatePro/AceTranslatePro/ui'

# 中文 → 英文 key 映射
CN_TO_EN = {
    "文本翻译": "Text Translation",
    "划词翻译": "Selection Translation",
    "截图翻译": "Screenshot Translation",
    "图片翻译": "Image Translation",
    "文件翻译": "File Translation",
    "设置": "Settings",
    "翻译": "Translate",
    "翻译中…": "Translating…",
    "翻译结果": "Translation Result",
    "翻译结果…": "Translation Result…",
    "翻译引擎错误: ": "Translation engine error: ",
    "文件翻译错误: ": "File translation error: ",
    "截图翻译错误: ": "Screenshot translation error: ",
    "图片翻译错误: ": "Image translation error: ",
    "翻译出错: ": "Translation error: ",
    "翻译引擎": "Translator",
    "翻译模型": "Translation Model",
    "翻译历史": "Translation History",
    "朗读": "Read Aloud",
    "复制": "Copy",
    "粘贴": "Paste",
    "清空": "Clear",
    "取消": "Cancel",
    "确定": "OK",
    "确认": "Confirm",
    "提示": "Prompt",
    "错误": "Error",
    "警告": "Warning",
    "完成": "Done",
    "等待截图…": "Waiting for screenshot…",
    "上传文件": "Upload File",
    "选择文件": "Select File",
    "保存": "Save",
    "删除": "Delete",
    "添加": "Add",
    "上传": "Upload",
    "下载": "Download",
    "模型": "Model",
    "引擎": "Engine",
    "启动": "Start",
    "停止": "Stop",
    "加载": "Load",
    "识别": "Recognize",
    "状态": "Status",
    "源语言:": "Source Language:",
    "目标语言:": "Target Language:",
    "原文": "Source Text",
    "自动检测": "Auto Detect",
    "自动复制": "Auto Copy",
    "窗口置顶": "Stay on Top",
    "默认语言": "Default Language",
    "快捷键": "Hotkey",
    "快捷键冲突": "Hotkey Conflict",
    "快捷键注册失败": "Hotkey Registration Failed",
    "截图预览": "Screenshot Preview",
    "识别结果": "Recognition Result",
    "OCR 识别文本…": "OCR Text…",
    "OCR 识别截图…": "Recognizing…",
    "截图图像为空": "Screenshot is empty",
    "请输入要翻译的文本…": "Enter text to translate…",
    "0 字符": "0 characters",
    "就绪": "Ready",
    "正在处理中，请等待…": "Processing, please wait…",
    "正在加载配置…": "Loading config…",
    "正在加载引擎…": "Loading engines…",
    "引擎加载完成": "Engines loaded",
    "正在初始化界面…": "Initializing UI…",
    "启动完成": "Startup complete",
    "AceTranslatePro 已在运行中，请勿重复启动。": "AceTranslatePro is already running.",
    "设置划词翻译快捷键": "Set Selection Hotkey",
    "设置截图快捷键": "Set Screenshot Hotkey",
    "按下新的快捷键组合，至少包含 Ctrl 或 Alt 键": "Press new hotkey (Ctrl or Alt required)",
    "请至少包含 Ctrl 或 Alt 修饰键。\n例如：Ctrl+Shift+D": "Must include Ctrl or Alt.\nExample: Ctrl+Shift+D",
    "该快捷键已被划词翻译使用，请选择其他组合。": "This hotkey is used by Selection Translation.",
    "该快捷键已被截图翻译使用，请选择其他组合。": "This hotkey is used by Screenshot Translation.",
    "已恢复为默认 Ctrl+Shift+C。": "Restored to Ctrl+Shift+C.",
    "已恢复为默认 Ctrl+Shift+Z。": "Restored to Ctrl+Shift+Z.",
    "选中的文本将显示在这里…": "Selected text will appear here…",
    "翻译结果将显示在这里…": "Translation result will appear here…",
    "划词翻译记录将显示在这里…": "Translation history will appear here…",
    "点击「截图翻译」按钮或按快捷键截取屏幕区域，自动识别并翻译": "Capture screen area for OCR and translation",
    "正在翻译…": "Translating…",
    "译文已复制": "Copied",
    "当前文本": "Current Text",
    "去扭曲": "Deskew",
    "增强": "Enhance",
    "版面阈值:": "Layout Threshold:",
    "DPI:": "DPI:",
    "上传文件列表": "File List",
    "翻译完成": "Translation Complete",
    "已下载到: ": "Downloaded to: ",
    "保存失败": "Save Failed",
    "启动时加载引擎": "Load Engines on Startup",
    "关闭可减少启动时间和内存占用，未加载的引擎在翻译时会自动提示": "Disable to reduce startup time. Engines load on demand.",
    "OCR 引擎": "OCR Engine",
    "公式识别": "Formula Recognition",
    "版面分析": "Layout Analysis",
    "图片矫正": "Image Correction",
    "语音识别": "Speech Recognition",
    "GPU 设置": "GPU Settings",
    "关闭 GPU 加速可降低显存占用，修改后需重启应用生效": "Disable GPU to reduce VRAM. Restart required.",
    "启用全部 GPU 加速": "Enable All GPU Acceleration",
    "版面分析启用 GPU": "Layout GPU",
    "OCR 启用 GPU": "OCR GPU",
    "公式识别启用 GPU": "VLM GPU",
    "图片矫正启用 GPU": "Image Correction GPU",
    "翻译引擎启用 GPU": "Translator GPU",
    "语音识别启用 GPU": "ASR GPU",
    "OCR 模型大小:": "OCR Model Size:",
    "tiny（轻量）": "Tiny",
    "small（中等）": "Small",
    "medium（高精度）": "Medium",
    "翻译模型:": "Translation Model:",
    "刷新模型列表": "Refresh Models",
    "OCR 引擎未加载，请先在设置中勾选「启动时加载引擎 → OCR 引擎」，然后重启应用。": "OCR engine not loaded. Enable it in Settings then restart.",
    "OCR 引擎加载失败，请检查模型文件是否存在。\n路径：models/ocr/[tiny/small/medium]/": "OCR engine load failed. Check models at: models/ocr/[tiny/small/medium]/",
    "截图翻译不可用": "Screenshot Unavailable",
    "该快捷键与当前设置相同，无需修改": "This hotkey is unchanged.",
    "录音中…点击 🎤 停止": "Recording… click to stop",
    "测试模式：读取 test.wav…": "Test mode: reading test.wav…",
    "截图取消": "Screenshot cancelled",
    "图片为空": "Image is empty",
    "在文件夹中打开": "Open in Folder",
    "所有文件 (*)": "All Files (*)",
    "字符": "Characters",
    "设置快捷键": "Set Hotkey",
    "隐藏": "Hide",
    "显示": "Show",
    "帮助": "Help",
    "关于": "About",
    "关闭": "Close",
    "重试": "Retry",
    "全部": "All",
    "无": "None",
    "开": "ON",
    "关": "OFF",
    "编辑": "Edit",
    "中文": "Chinese",
    "英语": "English",
    "日语": "Japanese",
    "韩语": "Korean",
    "法语": "French",
    "德语": "German",
    "西班牙语": "Spanish",
    "俄语": "Russian",
    "阿拉伯语": "Arabic",
    "葡萄牙语": "Portuguese",
    "意大利语": "Italian",
    "泰语": "Thai",
    "越南语": "Vietnamese",
    "印尼语": "Indonesian",
    "马来语": "Malay",
    "菲律宾语": "Filipino",
    "印地语": "Hindi",
    "繁体中文": "Traditional Chinese",
    "波兰语": "Polish",
    "捷克语": "Czech",
    "荷兰语": "Dutch",
    "高棉语": "Khmer",
    "缅甸语": "Burmese",
    "波斯语": "Persian",
    "古吉拉特语": "Gujarati",
    "乌尔都语": "Urdu",
    "泰卢固语": "Telugu",
    "马拉地语": "Marathi",
    "希伯来语": "Hebrew",
    "孟加拉语": "Bengali",
    "泰米尔语": "Tamil",
    "乌克兰语": "Ukrainian",
    "藏语": "Tibetan",
    "哈萨克语": "Kazakh",
    "蒙古语": "Mongolian",
    "维吾尔语": "Uyghur",
    "粤语": "Cantonese",
    "土耳其语": "Turkish",
    "马拉雅拉姆语": "Malayalam",
    "卡纳达语": "Kannada",
    "旁遮普语": "Punjabi",
    "输入或粘贴文本，快速翻译到目标语言": "Enter or paste text to translate",
    "选中任意应用中的文字，按快捷键弹出翻译窗口": "Select text in any app, press hotkey to translate",
    "请拖拽或选择输入文件": "Drag or select input file",
    "请输入要翻译的文本": "Enter text to translate",
    "请选择输入图片": "Select input image",
    "选择图片": "Select Image",
    "选择模型/DLL 目录": "Select Model/DLL Directory",
    "麦克风打开失败": "Microphone open failed",
    "语音输入": "Voice Input",
    "语音识别中…": "Speech recognition…",
    "语音识别完成": "Speech complete",
    "ASR DLL 接口错误": "ASR DLL Interface Error",
    "ASR 引擎未加载": "ASR Engine Not Loaded",
    "ASR 模型加载失败": "ASR Model Load Failed",
    "未找到 %1 语音包": "Voice %1 not found",
    "热键 %1 注册失败（错误码: %2），可能被其他程序占用。\n已恢复为默认 Ctrl+Shift+C。": "Hotkey %1 failed (error: %2). Restored to Ctrl+Shift+C.",
    "热键 %1 注册失败（错误码: %2），可能被其他程序占用。\n已恢复为默认 Ctrl+Shift+Z。": "Hotkey %1 failed (error: %2). Restored to Ctrl+Shift+Z.",
    "拖拽图片到此处，或点击上传": "Drag image here or click to upload",
    "拖拽图片预览…": "Image preview…",
    "拖拽文件到此处，或点击上传": "Drag files here or click to upload",
    "按快捷键弹出翻译窗口": "Press hotkey to translate",
    "翻译图片": "Translate Image",
    "翻译图片…": "Translating image…",
    "翻译完成后显示结果…": "Result shows after translation…",
    "原图": "Original",
    "图片已保存: ": "Image saved: ",
    "图片已复制": "Image copied",
    "保存图片": "Save Image",
    "保存图片失败": "Save Image Failed",
    "放大": "Zoom In",
    "缩小": "Zoom Out",
    "图片": "Image",
    "文本": "Text",
    "文件": "File",
    "大": "Large",
    "小": "Small",
    "中": "Medium",
    "处理中…": "Processing…",
    "处理文件: ": "Processing: ",
    "已完成": "Completed",
    "排队中": "Queued",
    "全部翻译完成（共 %1 个文件）": "All %1 files translated",
    "打开设置": "Open Settings",
    "显示主窗口": "Show Main Window",
    "退出": "Exit",
    "测试模式：找不到 test.wav": "Test mode: test.wav not found",
    "测试模式：读取完成，开始识别": "Test mode: loaded, recognizing",
    "点击停止录音": "Click to stop recording",
    "修改后需重启应用生效": "Requires restart",
    "保存文件": "Save File",
    "支持 PDF / Word / Excel / PPT / MD / TXT / 图片": "Supports PDF / Word / Excel / PPT / MD / TXT / Images",
    "无法加载图片": "Cannot load image",
    "无法加载预览": "Cannot load preview",
    "PNG 图片 (*.png)": "PNG Images (*.png)",
    "图片 (*.png *.jpg *.jpeg *.bmp *.tiff);;所有文件 (*)": "Images (*.png *.jpg *.jpeg *.bmp *.tiff);;All Files (*)",
    "支持的文件 (*.png *.jpg *.jpeg *.bmp *.tiff *.pdf *.docx *.xlsx *.pptx *.md *.txt)": "Supported Files (*.png *.jpg *.jpeg *.bmp *.tiff *.pdf *.docx *.xlsx *.pptx *.md *.txt)",
    "支持的文件 (*.png *.jpg *.jpeg *.bmp *.tiff *.pdf *.docx *.xlsx *.pptx *.md *.txt);;所有文件 (*)": "Supported Files (*.png *.jpg *.jpeg *.bmp *.tiff *.pdf *.docx *.xlsx *.pptx *.md *.txt);;All Files (*)",
    "界面语言": "Language",
    "语言切换将在重启后生效": "Language change takes effect after restart",
    "日本語": "Japanese",
    "未知错误（可能是 DLL 加载失败）": "Unknown error (DLL load failure)",
    "翻译出错": "Translation Error",
}

# 先不处理语言名称列表（populateLanguages 中的语言名），因为它们是动态值

# 遍历 ui/ 下所有 .cpp .h
pattern = re.compile(r'QStringLiteral\("((?:[^"\\]|\\.)*)"\)')
total = 0

for root, dirs, files in os.walk(ui_dir):
    for f in files:
        if not f.endswith(('.cpp', '.h')):
            continue
        path = os.path.join(root, f)
        with open(path, 'r', encoding='utf-8') as fp:
            content = fp.read()

        new_content = content
        changes = 0
        for m in pattern.finditer(content):
            text = m.group(1)
            if text in CN_TO_EN:
                en_key = CN_TO_EN[text]
                old = f'QStringLiteral("{text}")'
                new = f'tr("{en_key}")'
                if old in new_content:
                    new_content = new_content.replace(old, new, 1)
                    changes += 1
                    total += 1
                # also handle multi-line
                old2 = f'QStringLiteral(\n "{text}")'
                if old2 in new_content:
                    new_content = new_content.replace(old2, f'tr("{en_key}")', 1)
                    changes += 1
                    total += 1

        if changes > 0:
            with open(path, 'w', encoding='utf-8') as f:
                f.write(new_content)
            print(f'{os.path.basename(path)}: {changes} replacements')

print(f'\nTotal: {total}')
